/* =====================================================================
   Chapter 4: The Market Forces of Supply and Demand
   Question bank for the Supply & Demand Market Simulator
   ---------------------------------------------------------------------
   Each question has:
     cat : topic label shown to the student
     q   : question text
     o   : four answer options
     a   : index (0-3) of the correct option
     e   : explanation shown after answering
     g   : (optional) graph preset used by the "Show on graph" button
           d = demand-side variables, s = supply-side variables
           (values are in lattes; the simulator translates them into shifts)
           price = a fixed market price (leave out to let price settle)
           market = label for the good shown on the chart
   To edit a question, just change the text. To add one, copy a block.
   ===================================================================== */
const CH4_QUESTIONS = [

/* ---------- A. Markets and competition ---------- */
{ cat: "Markets & competition",
  q: "In economics, a market is best defined as:",
  o: ["A physical building where trading happens", "A group of buyers and sellers of a particular good or service", "Any place where the government sets prices", "A group of firms that produce the same good"],
  a: 1, e: "A market is a group of buyers and sellers of a particular good or service. It does not need a physical location." },
{ cat: "Markets & competition",
  q: "In a market, buyers as a group determine the ______ for a product and sellers as a group determine the ______.",
  o: ["supply; demand", "price; quantity", "demand; supply", "quantity; price"],
  a: 2, e: "Buyers determine demand; sellers determine supply. Together they determine price and quantity." },
{ cat: "Markets & competition",
  q: "Which feature describes a competitive market?",
  o: ["One seller sets the price", "Many buyers and sellers, each with a negligible effect on the market price", "Goods are always different from each other", "Buyers can bargain the price down"],
  a: 1, e: "In a competitive market there are so many buyers and sellers that no single one can affect the price." },
{ cat: "Markets & competition",
  q: "In a perfectly competitive market, buyers and sellers are described as:",
  o: ["Price makers", "Price takers", "Price setters", "Monopolists"],
  a: 1, e: "Because no single buyer or seller can influence the market price, everyone must take the price as given." },
{ cat: "Markets & competition",
  q: "Which is NOT a condition of a perfectly competitive market?",
  o: ["All goods offered are exactly the same", "Many buyers and many sellers", "Each seller can set its own price above the market price", "No single buyer can affect the market price"],
  a: 2, e: "A perfectly competitive seller cannot charge more than the market price; buyers would simply go elsewhere." },
{ cat: "Markets & competition",
  q: "Why do economists study perfectly competitive markets first, even though few exist in the real world?",
  o: ["They are the only markets that matter", "The model is easier to learn and still teaches a lot about how markets work", "Real markets cannot be modeled", "Governments require it"],
  a: 1, e: "The perfectly competitive model is a simple starting point that still explains a great deal, and it makes the more complex models easier to learn." },

/* ---------- B. Demand basics, schedule and curve ---------- */
{ cat: "Demand",
  q: "Quantity demanded is the amount of a good that buyers are:",
  o: ["Willing to purchase", "Able to purchase", "Willing and able to purchase", "Required to purchase"],
  a: 2, e: "Both willingness and ability matter. Wanting a latte you cannot afford does not count as quantity demanded." },
{ cat: "Demand",
  q: "According to the law of demand, other things equal, when the price of a good rises:",
  o: ["Quantity demanded falls", "Quantity demanded rises", "Demand shifts right", "Supply falls"],
  a: 0, e: "Law of demand: higher price, lower quantity demanded. This is a movement along the curve, not a shift.",
  g: { price: 5, market: "lattes" } },
{ cat: "Demand",
  q: "A demand schedule is:",
  o: ["A graph showing price and quantity demanded", "A table showing the relationship between price and quantity demanded", "A list of the reasons people buy things", "A government plan for rationing goods"],
  a: 1, e: "A schedule is a table; a curve is the graph drawn from that table." },
{ cat: "Demand",
  q: "On a demand curve, which variable is on the vertical axis?",
  o: ["Quantity", "Income", "Price", "Time"],
  a: 2, e: "By convention, price goes on the vertical (y) axis and quantity on the horizontal (x) axis." },
{ cat: "Demand",
  q: "Sam's demand schedule for lattes shows 16 at $0, 14 at $1, 12 at $2, 10 at $3, 8 at $4, 6 at $5 and 4 at $6. How many lattes does Sam demand at $4?",
  o: ["6", "8", "10", "12"],
  a: 1, e: "Reading the schedule: at a price of $4.00, Sam's quantity demanded is 8 lattes." },
{ cat: "Demand",
  q: "Using Sam's schedule (16 at $0 falling by 2 for each $1 rise in price), what happens to his quantity demanded when the price rises from $2 to $3?",
  o: ["It rises from 10 to 12", "It falls from 12 to 10", "It stays at 12", "It falls from 12 to 8"],
  a: 1, e: "At $2 Sam demands 12; at $3 he demands 10. This is a movement along Sam's demand curve." },
{ cat: "Demand",
  q: "Sam's demand schedule obeys the law of demand because:",
  o: ["Quantity demanded rises as price rises", "Quantity demanded falls as price rises", "Quantity demanded does not change with price", "He always buys the same number of lattes"],
  a: 1, e: "Every $1 increase in price lowers Sam's quantity demanded by 2 lattes, so price and quantity demanded move in opposite directions." },
{ cat: "Demand",
  q: "The demand curve slopes downward because:",
  o: ["Sellers lower prices over time", "Higher prices reduce the quantity buyers are willing and able to buy", "Buyers prefer expensive goods", "Income rises when prices fall"],
  a: 1, e: "The downward slope is the graphical picture of the law of demand." },
{ cat: "Demand",
  q: "In the simulator, the market demand for lattes is QD = 24 − 3P. What is quantity demanded at a price of $2?",
  o: ["15", "18", "21", "24"],
  a: 1, e: "QD = 24 − 3(2) = 18 lattes.", g: { price: 2, market: "lattes" } },
{ cat: "Demand",
  q: "Using market demand QD = 24 − 3P, at what price does quantity demanded fall to 6 lattes?",
  o: ["$4", "$5", "$6", "$8"],
  a: 2, e: "24 − 3P = 6 gives 3P = 18, so P = $6.", g: { price: 6, market: "lattes" } },

/* ---------- C. Market demand vs individual demand ---------- */
{ cat: "Market vs individual demand",
  q: "Market demand is:",
  o: ["The demand of the largest buyer", "The average of all individual demands", "The sum of all individual demands for a good", "The demand of the government"],
  a: 2, e: "Market demand adds up the quantity demanded by every buyer at each price." },
{ cat: "Market vs individual demand",
  q: "To build the market demand curve from individual demand curves, we add them:",
  o: ["Vertically (add the prices)", "Horizontally (add the quantities at each price)", "Diagonally", "Only at the equilibrium price"],
  a: 1, e: "At each price, we add the quantities demanded by each buyer. That is a horizontal sum." },
{ cat: "Market vs individual demand",
  q: "Sam and Dean are the only buyers of lattes. At $3, Sam demands 10 and Dean demands 5. Market quantity demanded at $3 is:",
  o: ["5", "10", "15", "50"],
  a: 2, e: "10 + 5 = 15 lattes.", g: { price: 3, market: "lattes" } },
{ cat: "Market vs individual demand",
  q: "At $0, Sam demands 16 lattes and Dean demands 8. At $1, Sam demands 14 and Dean 7. What is the market quantity demanded at $1?",
  o: ["24", "21", "18", "14"],
  a: 1, e: "14 + 7 = 21 lattes. (At $0 it is 16 + 8 = 24.)", g: { price: 1, market: "lattes" } },
{ cat: "Market vs individual demand",
  q: "At $6, Sam demands 4 lattes and Dean demands 2. If a third buyer, Cas, who demands 3 lattes at $6 joins the market, market quantity demanded at $6 becomes:",
  o: ["6", "9", "3", "12"],
  a: 1, e: "4 + 2 + 3 = 9 lattes. Adding a buyer raises quantity demanded at every price, which shifts market demand right.",
  g: { d: { buyers: 3 }, price: 6, market: "lattes" } },
{ cat: "Market vs individual demand",
  q: "The chapter's two-buyer example (Sam and Dean) violates which condition of perfect competition?",
  o: ["Goods are identical", "Many buyers", "Sellers are price takers", "Prices are flexible"],
  a: 1, e: "Two buyers is far from 'many', but the example still shows how market demand is the sum of individual demands." },

/* ---------- D. Demand shifters ---------- */
{ cat: "Demand shifters",
  q: "The 'other things' held constant along a demand curve are called:",
  o: ["Price determinants of demand", "Non-price determinants of demand", "Supply factors", "Equilibrium conditions"],
  a: 1, e: "Non-price determinants (income, prices of related goods, tastes, expectations, number of buyers) shift the whole demand curve." },
{ cat: "Demand shifters",
  q: "An increase in the number of buyers of lattes will:",
  o: ["Shift the demand curve to the right", "Shift the demand curve to the left", "Cause a movement along the demand curve", "Shift the supply curve to the right"],
  a: 0, e: "More buyers means more lattes demanded at every price, so the demand curve shifts right.",
  g: { d: { buyers: 8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "A new college opens near a coffee shop, bringing many new coffee drinkers to town. In the latte market this:",
  o: ["Shifts supply right", "Shifts demand right", "Shifts demand left", "Moves along the demand curve"],
  a: 1, e: "More buyers is a non-price determinant of demand. Demand shifts right; price and quantity both rise.",
  g: { d: { buyers: 8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "For a normal good, an increase in income:",
  o: ["Decreases demand", "Increases demand", "Has no effect on demand", "Increases supply"],
  a: 1, e: "Normal good: higher income, higher demand (curve shifts right). Examples: laptops, branded clothes, luxury watches.",
  g: { d: { income: 8, incomeType: "normal" }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "For an inferior good, an increase in income:",
  o: ["Shifts demand right", "Shifts demand left", "Shifts supply left", "Causes a movement along the demand curve"],
  a: 1, e: "Inferior good: higher income, lower demand. Examples: instant ramen, fake watches.",
  g: { d: { income: 8, incomeType: "inferior" }, market: "instant ramen" } },
{ cat: "Demand shifters",
  q: "Which of the following is most likely an inferior good?",
  o: ["Luxury watches", "Branded clothing", "Instant ramen noodles", "Laptops"],
  a: 2, e: "People tend to buy less instant ramen as their income rises, which is the definition of an inferior good." },
{ cat: "Demand shifters",
  q: "During a recession incomes fall. If lattes are a normal good, the demand for lattes will:",
  o: ["Shift right", "Shift left", "Not change", "Become a supply change"],
  a: 1, e: "Lower income lowers demand for a normal good, shifting the curve left. Price and quantity both fall.",
  g: { d: { income: -8, incomeType: "normal" }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "Two goods are substitutes if an increase in the price of one leads to:",
  o: ["A decrease in demand for the other", "An increase in demand for the other", "No change in demand for the other", "An increase in supply of the other"],
  a: 1, e: "Substitutes: when pizza gets pricier, people buy more hamburgers instead. Demand for the other good rises." },
{ cat: "Demand shifters",
  q: "Which pair of goods are substitutes?",
  o: ["Computers and software", "Bagels and cream cheese", "Coke and Pepsi", "College tuition and textbooks"],
  a: 2, e: "Coke and Pepsi are substitutes; the other pairs are complements that are used together." },
{ cat: "Demand shifters",
  q: "The price of cappuccinos (a substitute for lattes) rises. In the latte market:",
  o: ["Demand for lattes shifts right", "Demand for lattes shifts left", "Supply of lattes shifts right", "Quantity demanded of lattes falls along the curve"],
  a: 0, e: "When a substitute becomes more expensive, buyers switch to lattes. Latte demand shifts right.",
  g: { d: { subs: 8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "Two goods are complements if an increase in the price of one leads to:",
  o: ["An increase in demand for the other", "A decrease in demand for the other", "An increase in supply of the other", "No change in the other market"],
  a: 1, e: "Complements are used together. If computers get pricier, people buy fewer computers and therefore less software." },
{ cat: "Demand shifters",
  q: "Which pair of goods are complements?",
  o: ["Laptops and tablets", "Music CDs and music downloads", "Milk and coffee", "Pizza and hamburgers"],
  a: 2, e: "Milk and coffee are consumed together, so they are complements. The other pairs are substitutes." },
{ cat: "Demand shifters",
  q: "Pastries are a complement to lattes. If the price of pastries falls, the demand for lattes will:",
  o: ["Shift left", "Shift right", "Not change", "Become more elastic"],
  a: 1, e: "Cheaper pastries mean more pastries bought, and more lattes to go with them. Latte demand shifts right.",
  g: { d: { comps: -8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "The price of iPods falls. What happens in the market for music downloads (a complement)?",
  o: ["Demand for downloads shifts right", "Demand for downloads shifts left", "The demand curve does not shift", "Supply of downloads shifts left"],
  a: 0, e: "Active Learning 1A: iPods and downloads are complements. A cheaper iPod raises demand for downloads (shift right).",
  g: { d: { comps: -8 }, market: "music downloads" } },
{ cat: "Demand shifters",
  q: "The price of music CDs falls. What happens in the market for music downloads (a substitute)?",
  o: ["Demand for downloads shifts right", "Demand for downloads shifts left", "Movement along the download demand curve", "Supply of downloads shifts right"],
  a: 1, e: "Active Learning 1C: CDs and downloads are substitutes. Cheaper CDs pull buyers away, so demand for downloads shifts left.",
  g: { d: { subs: -8 }, market: "music downloads" } },
{ cat: "Demand shifters",
  q: "In the 1990s the Atkins diet became popular and people wanted more eggs. This is an example of a demand shift caused by:",
  o: ["Income", "Prices of related goods", "Tastes", "Number of buyers"],
  a: 2, e: "A change in tastes toward a good shifts its demand curve right.",
  g: { d: { tastes: 8 }, market: "eggs" } },
{ cat: "Demand shifters",
  q: "A move toward veganism would most directly cause:",
  o: ["A rightward shift in demand for meat", "A leftward shift in demand for meat", "A movement along the demand curve for meat", "A rightward shift in supply of meat"],
  a: 1, e: "Tastes shift away from meat, so meat demand shifts left.",
  g: { d: { tastes: -8 }, market: "meat" } },
{ cat: "Demand shifters",
  q: "People expect their incomes to rise next year. The current demand for meals at expensive restaurants will most likely:",
  o: ["Increase now", "Decrease now", "Stay the same until incomes actually rise", "Turn into a supply shift"],
  a: 0, e: "Expectations of higher future income raise current demand (shift right).",
  g: { d: { dexp: 8 }, market: "restaurant meals" } },
{ cat: "Demand shifters",
  q: "Buyers expect the price of lattes to rise sharply next month. Today's demand for lattes will:",
  o: ["Shift left", "Shift right", "Not change", "Move along the curve"],
  a: 1, e: "Expecting higher prices leads people to buy more now, shifting current demand right.",
  g: { d: { dexp: 8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "Worries about future job security cause people to fear their incomes will fall. The demand for new cars today will:",
  o: ["Shift right", "Shift left", "Not change", "Shift only after incomes fall"],
  a: 1, e: "Expectations of lower future income reduce current demand for big purchases like cars.",
  g: { d: { dexp: -8 }, market: "new cars" } },
{ cat: "Demand shifters",
  q: "Which of the following would NOT shift the demand curve for lattes?",
  o: ["A rise in buyers' income", "A change in the price of lattes", "A rise in the price of cappuccinos", "A new health study praising coffee"],
  a: 1, e: "A change in the good's own price causes a movement along the demand curve, not a shift.",
  g: { price: 4, market: "lattes" } },
{ cat: "Demand shifters",
  q: "Which list contains ONLY non-price determinants of demand?",
  o: ["Income, tastes, price of the good", "Income, prices of related goods, tastes, expectations, number of buyers", "Technology, input prices, number of sellers", "Price of the good and number of sellers"],
  a: 1, e: "These five variables shift demand. Technology and input prices belong to supply; the good's own price moves along the curve." },
{ cat: "Demand shifters",
  q: "A public health campaign with warnings on cigarette packs is meant to reduce smoking by:",
  o: ["Shifting the demand curve for cigarettes left", "Moving along the demand curve", "Shifting supply left", "Raising the equilibrium price"],
  a: 0, e: "The campaign changes tastes, shifting demand left. A tax, by contrast, raises price and moves along the curve.",
  g: { d: { tastes: -8 }, market: "cigarettes" } },

/* ---------- E. Supply basics, schedule and curve ---------- */
{ cat: "Supply",
  q: "Quantity supplied is the amount of a good that sellers are:",
  o: ["Willing and able to sell", "Forced to sell", "Able to produce in a year", "Willing to give away"],
  a: 0, e: "Quantity supplied combines willingness and ability to sell at a given price." },
{ cat: "Supply",
  q: "According to the law of supply, other things equal, when the price of a good rises:",
  o: ["Quantity supplied falls", "Quantity supplied rises", "Supply shifts left", "Demand rises"],
  a: 1, e: "Higher prices make selling more profitable, so sellers offer more. This is a movement along the supply curve.",
  g: { price: 5, market: "lattes" } },
{ cat: "Supply",
  q: "Starbucks' supply schedule is 0 lattes at $0, 3 at $1, 6 at $2, 9 at $3, 12 at $4, 15 at $5 and 18 at $6. How many lattes does Starbucks supply at $5?",
  o: ["9", "12", "15", "18"],
  a: 2, e: "Reading the schedule: at $5.00 Starbucks supplies 15 lattes." },
{ cat: "Supply",
  q: "Starbucks' supply schedule obeys the law of supply because:",
  o: ["Quantity supplied rises by 3 each time price rises by $1", "Quantity supplied falls as price rises", "Quantity supplied is constant", "Starbucks sets its own price"],
  a: 0, e: "Price and quantity supplied move in the same direction, which is exactly the law of supply." },
{ cat: "Supply",
  q: "The supply curve slopes upward because:",
  o: ["Buyers want more at higher prices", "Higher prices make production more profitable, so sellers supply more", "Costs always fall as price rises", "The government requires it"],
  a: 1, e: "The upward slope is the graphical picture of the law of supply." },
{ cat: "Supply",
  q: "In the simulator, market supply of lattes is QS = 5P. What is quantity supplied at a price of $4?",
  o: ["12", "15", "20", "25"],
  a: 2, e: "QS = 5 × 4 = 20 lattes.", g: { price: 4, market: "lattes" } },
{ cat: "Supply",
  q: "Using market supply QS = 5P, at what price is quantity supplied equal to 10 lattes?",
  o: ["$1", "$2", "$3", "$5"],
  a: 1, e: "5P = 10 gives P = $2.", g: { price: 2, market: "lattes" } },
{ cat: "Supply",
  q: "A supply schedule is:",
  o: ["A graph of supply", "A table showing price and quantity supplied", "A list of sellers", "A production timetable"],
  a: 1, e: "Like the demand schedule, it is a table; the supply curve is drawn from it." },

/* ---------- F. Market supply vs individual supply ---------- */
{ cat: "Market vs individual supply",
  q: "Market supply is:",
  o: ["The supply of the largest firm", "The sum of the supplies of all sellers", "The average of all sellers' supply", "The supply the government allows"],
  a: 1, e: "Market supply adds up quantity supplied by every seller at each price (a horizontal sum)." },
{ cat: "Market vs individual supply",
  q: "Starbucks and Peet's are the only sellers. At $3 Starbucks supplies 9 lattes and Peet's supplies 6. Market quantity supplied at $3 is:",
  o: ["9", "6", "15", "54"],
  a: 2, e: "9 + 6 = 15 lattes.", g: { price: 3, market: "lattes" } },
{ cat: "Market vs individual supply",
  q: "At $6, Starbucks supplies 18 lattes and Peet's supplies 12. Market quantity supplied at $6 is:",
  o: ["18", "24", "30", "36"],
  a: 2, e: "18 + 12 = 30 lattes.", g: { price: 6, market: "lattes" } },
{ cat: "Market vs individual supply",
  q: "A third coffee shop opens and supplies 4 lattes at $2. If Starbucks supplies 6 and Peet's supplies 4 at $2, the new market quantity supplied at $2 is:",
  o: ["10", "12", "14", "16"],
  a: 2, e: "6 + 4 + 4 = 14 lattes. A new seller raises quantity supplied at every price, shifting market supply right.",
  g: { s: { sellers: 4 }, price: 2, market: "lattes" } },

/* ---------- G. Supply shifters ---------- */
{ cat: "Supply shifters",
  q: "Which list contains ONLY non-price determinants of supply?",
  o: ["Input prices, technology, expectations, number of sellers", "Income, tastes, number of buyers", "Price of the good, technology", "Prices of substitutes and complements"],
  a: 0, e: "These four variables shift supply. Income and tastes belong to demand; the good's own price moves along the curve." },
{ cat: "Supply shifters",
  q: "Supply is ______ related to input prices.",
  o: ["Positively", "Negatively", "Not", "Proportionally"],
  a: 1, e: "Higher input prices raise costs and reduce supply; lower input prices increase supply." },
{ cat: "Supply shifters",
  q: "The price of milk (an input for lattes) falls. In the latte market:",
  o: ["Supply shifts right", "Supply shifts left", "Demand shifts right", "Quantity supplied falls along the curve"],
  a: 0, e: "Cheaper inputs make production more profitable at each price, so sellers supply more. Supply shifts right.",
  g: { s: { inputs: -8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "Wages for baristas rise. The supply curve for lattes will:",
  o: ["Shift right", "Shift left", "Not move", "Become the demand curve"],
  a: 1, e: "Wages are an input price. Higher input prices raise costs and shift supply left, raising price and lowering quantity.",
  g: { s: { inputs: 8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "A cost-saving technological improvement has the same effect on supply as:",
  o: ["A rise in input prices", "A fall in input prices", "A fall in the number of sellers", "A rise in the price of the good"],
  a: 1, e: "Both lower the cost of producing each unit and shift the supply curve right.",
  g: { s: { tech: 8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "A new espresso machine lets each barista make lattes twice as fast. The supply of lattes:",
  o: ["Shifts left", "Shifts right", "Does not change", "Moves along the curve"],
  a: 1, e: "Better technology means fewer inputs per latte, so supply increases (shifts right).",
  g: { s: { tech: 8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "An increase in the number of sellers:",
  o: ["Decreases quantity supplied at each price", "Increases quantity supplied at each price and shifts supply right", "Shifts demand right", "Has no effect on supply"],
  a: 1, e: "More sellers means more output at every price, which is a rightward shift of supply.",
  g: { s: { sellers: 8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "Several coffee shops close permanently. In the latte market this:",
  o: ["Shifts supply left, raising price", "Shifts supply right, lowering price", "Shifts demand left", "Causes a movement along the supply curve"],
  a: 0, e: "Fewer sellers reduce supply. The curve shifts left, so price rises and quantity falls.",
  g: { s: { sellers: -8 }, market: "lattes" } },
{ cat: "Supply shifters",
  q: "Events in the Middle East lead Texas oilfield owners to expect higher oil prices soon. Today's oil supply will:",
  o: ["Shift right", "Shift left", "Not change", "Move along the curve"],
  a: 1, e: "Sellers hold back some oil to sell later at the higher price, so current supply shifts left.",
  g: { s: { sexp: 8 }, market: "oil" } },
{ cat: "Supply shifters",
  q: "Sellers can adjust current supply in response to expected future prices only if:",
  o: ["The good is perishable", "The good can be stored (not perishable)", "The government allows it", "Demand is also changing"],
  a: 1, e: "You cannot save fresh lattes for next month, but you can store oil. Expectations matter for storable goods." },
{ cat: "Supply shifters",
  q: "A technological advance lets tax return software be produced at lower cost. The supply curve for the software:",
  o: ["Does not shift", "Shifts right", "Shifts left", "Becomes horizontal"],
  a: 1, e: "Active Learning 2B: lower production cost shifts supply right; at each price quantity supplied rises.",
  g: { s: { tech: 8 }, market: "tax software" } },
{ cat: "Supply shifters",
  q: "Professional tax preparers raise the price of their services. What happens to the SUPPLY curve of tax return software?",
  o: ["Shifts right", "Shifts left", "It does not shift; the demand curve for software shifts instead", "Moves down along the curve"],
  a: 2, e: "Active Learning 2C (trick question): professional preparers are a substitute for the software, so this shifts DEMAND for software right, not supply.",
  g: { d: { subs: 8 }, market: "tax software" } },

/* ---------- H. Shift vs movement along the curve ---------- */
{ cat: "Shift vs movement",
  q: "A 'change in quantity demanded' is:",
  o: ["A shift of the demand curve", "A movement along a fixed demand curve caused by a price change", "Caused by a change in income", "The same as a change in demand"],
  a: 1, e: "Only a change in the good's own price causes a movement along the curve. Everything else shifts it.",
  g: { price: 5, market: "lattes" } },
{ cat: "Shift vs movement",
  q: "A 'change in demand' is:",
  o: ["A movement along the demand curve", "A shift of the demand curve caused by a non-price determinant", "Caused only by a change in price", "A change in quantity demanded"],
  a: 1, e: "Demand refers to the position of the whole curve; it shifts when a non-price determinant changes.",
  g: { d: { buyers: 8 }, market: "lattes" } },
{ cat: "Shift vs movement",
  q: "A 'change in supply' occurs when:",
  o: ["The price of the good changes", "A non-price determinant of supply such as technology or costs changes", "Buyers' income changes", "Quantity supplied changes along the curve"],
  a: 1, e: "Supply refers to the position of the supply curve; a change in supply is a shift.",
  g: { s: { tech: 8 }, market: "lattes" } },
{ cat: "Shift vs movement",
  q: "A 'change in quantity supplied' occurs when:",
  o: ["Technology improves", "Input prices rise", "The price of the good changes", "The number of sellers changes"],
  a: 2, e: "A price change moves sellers along a fixed supply curve; the other three shift the curve.",
  g: { price: 5, market: "lattes" } },
{ cat: "Shift vs movement",
  q: "Handy rule: if the variable that changes is measured on one of the axes of the graph, then:",
  o: ["The curve shifts", "You move along the curve", "Both curves shift", "Nothing happens"],
  a: 1, e: "Price is on the axis, so a price change moves you along the curve. Variables not on the axes (income, costs...) shift the curve." },
{ cat: "Shift vs movement",
  q: "The price of music downloads falls. In the market for music downloads:",
  o: ["Demand shifts right", "Demand shifts left", "The demand curve does not shift; there is a movement down along it", "Supply shifts right"],
  a: 2, e: "Active Learning 1B: the good's own price changed, so we move along the demand curve to a lower price and higher quantity.",
  g: { price: 2, market: "music downloads" } },
{ cat: "Shift vs movement",
  q: "Retailers cut the price of tax return software. The supply curve for the software:",
  o: ["Shifts left", "Shifts right", "Does not shift; there is a movement down along it to a lower quantity", "Disappears"],
  a: 2, e: "Active Learning 2A: a change in the good's own price moves sellers along the supply curve to a lower P and lower Q.",
  g: { price: 2, market: "tax software" } },
{ cat: "Shift vs movement",
  q: "Set the market price of lattes to $5 in the simulator. Compared with equilibrium, what has happened?",
  o: ["Demand has shifted left", "Quantity demanded fell and quantity supplied rose along fixed curves", "Supply has shifted right", "Both curves shifted"],
  a: 1, e: "Neither curve moved. At $5, QD = 9 and QS = 25: movements along both curves.",
  g: { price: 5, market: "lattes" } },

/* ---------- I. Equilibrium ---------- */
{ cat: "Equilibrium",
  q: "Market equilibrium occurs where:",
  o: ["Quantity supplied equals quantity demanded", "Supply equals price", "Buyers get everything they want", "The government sets the price"],
  a: 0, e: "Equilibrium is the point where the supply and demand curves intersect: QS = QD.",
  g: { market: "lattes" } },
{ cat: "Equilibrium",
  q: "The equilibrium price is:",
  o: ["The highest price sellers can charge", "The price at which quantity supplied equals quantity demanded", "The lowest price buyers will pay", "The average of all prices"],
  a: 1, e: "At the equilibrium price the market clears: everything offered for sale is bought." },
{ cat: "Equilibrium",
  q: "The equilibrium quantity is:",
  o: ["The maximum quantity sellers can produce", "The quantity supplied and demanded at the equilibrium price", "The quantity buyers want at a price of zero", "Always 100 units"],
  a: 1, e: "At the equilibrium price, QS = QD, and that common amount is the equilibrium quantity." },
{ cat: "Equilibrium",
  q: "Latte market: P=$2 gives QD 18 and QS 10; P=$3 gives QD 15 and QS 15; P=$4 gives QD 12 and QS 20. The equilibrium price and quantity are:",
  o: ["$2 and 18", "$3 and 15", "$4 and 12", "$4 and 20"],
  a: 1, e: "Only at $3 is quantity demanded equal to quantity supplied (15 lattes).",
  g: { market: "lattes" } },
{ cat: "Equilibrium",
  q: "Solve for equilibrium: QD = 24 − 3P and QS = 5P. The equilibrium price is:",
  o: ["$2", "$3", "$4", "$5"],
  a: 1, e: "24 − 3P = 5P gives 8P = 24, so P = $3. Then Q = 5(3) = 15.",
  g: { market: "lattes" } },
{ cat: "Equilibrium",
  q: "If demand rises to QD = 32 − 3P (8 more buyers) while supply stays QS = 5P, the new equilibrium price is:",
  o: ["$3", "$3.50", "$4", "$5"],
  a: 2, e: "32 − 3P = 5P gives 8P = 32, so P = $4 and Q = 20. Demand shifted right: P and Q both rose.",
  g: { d: { buyers: 8 }, market: "lattes" } },
{ cat: "Equilibrium",
  q: "If supply rises to QS = 5P + 8 (cheaper milk) while demand stays QD = 24 − 3P, the new equilibrium price is:",
  o: ["$2", "$2.50", "$3", "$4"],
  a: 0, e: "24 − 3P = 5P + 8 gives 8P = 16, so P = $2 and Q = 18. Supply shifted right: P fell and Q rose.",
  g: { s: { inputs: -8 }, market: "lattes" } },
{ cat: "Equilibrium",
  q: "In a market economy, what naturally drives the market toward equilibrium?",
  o: ["Government orders", "The behavior of buyers and sellers responding to surpluses and shortages", "Advertising", "Fixed prices"],
  a: 1, e: "Sellers cut prices when they have a surplus and raise them when there is a shortage, moving the market to equilibrium." },

/* ---------- J. Surplus and shortage ---------- */
{ cat: "Surplus & shortage",
  q: "A surplus (excess supply) exists when:",
  o: ["Quantity demanded exceeds quantity supplied", "Quantity supplied exceeds quantity demanded", "Price is below equilibrium", "The market is in equilibrium"],
  a: 1, e: "Surplus: sellers want to sell more than buyers want to buy. This happens when the price is above equilibrium.",
  g: { price: 5, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "A shortage (excess demand) exists when:",
  o: ["Quantity supplied exceeds quantity demanded", "Quantity demanded exceeds quantity supplied", "Price is above equilibrium", "Supply shifts right"],
  a: 1, e: "Shortage: buyers want more than sellers offer. This happens when price is below equilibrium.",
  g: { price: 1, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "In the latte market the price is $5. QD = 9 and QS = 25. The surplus is:",
  o: ["9 lattes", "16 lattes", "25 lattes", "34 lattes"],
  a: 1, e: "Surplus = QS − QD = 25 − 9 = 16 lattes.",
  g: { price: 5, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "In the latte market the price is $1. QD = 21 and QS = 5. The shortage is:",
  o: ["5 lattes", "16 lattes", "21 lattes", "26 lattes"],
  a: 1, e: "Shortage = QD − QS = 21 − 5 = 16 lattes.",
  g: { price: 1, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "Using QD = 24 − 3P and QS = 5P, what is the situation at a price of $4?",
  o: ["Shortage of 8", "Surplus of 8", "Equilibrium", "Surplus of 20"],
  a: 1, e: "At $4, QD = 12 and QS = 20, so there is a surplus of 8 lattes.",
  g: { price: 4, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "Using QD = 24 − 3P and QS = 5P, what is the situation at a price of $2?",
  o: ["Surplus of 8", "Shortage of 8", "Equilibrium", "Shortage of 18"],
  a: 1, e: "At $2, QD = 18 and QS = 10, so there is a shortage of 8 lattes.",
  g: { price: 2, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "Facing a surplus, sellers will typically:",
  o: ["Raise the price", "Cut the price, which raises QD and lowers QS", "Shift the demand curve", "Produce even more"],
  a: 1, e: "Price cuts reduce the surplus and continue until the market reaches equilibrium.",
  g: { price: 5, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "Facing a shortage, sellers will typically:",
  o: ["Cut the price", "Raise the price, which lowers QD and raises QS", "Shift the supply curve", "Stop selling"],
  a: 1, e: "Higher prices reduce the shortage and continue rising until QD = QS.",
  g: { price: 1, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "When the market price is above the equilibrium price, there is a ______ and the price will ______.",
  o: ["shortage; rise", "surplus; fall", "surplus; rise", "shortage; fall"],
  a: 1, e: "Above equilibrium, QS > QD (surplus), and competition among sellers pushes the price down.",
  g: { price: 5, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "When the market price is below the equilibrium price, there is a ______ and the price will ______.",
  o: ["surplus; fall", "shortage; rise", "shortage; fall", "surplus; rise"],
  a: 1, e: "Below equilibrium, QD > QS (shortage), and buyers bid the price up.",
  g: { price: 1, market: "lattes" } },

/* ---------- K. Three-step analysis and double shifts ---------- */
{ cat: "Three-step analysis",
  q: "What is the FIRST step in analyzing how an event changes equilibrium?",
  o: ["Compare the old and new equilibrium", "Decide whether the event shifts supply, demand, or both", "Decide the direction of the shift", "Draw the new curve"],
  a: 1, e: "Step 1: which curve shifts? Step 2: which direction? Step 3: compare the initial and new equilibrium." },
{ cat: "Three-step analysis",
  q: "The price of gasoline rises. In the market for electric cars, which curve shifts and why?",
  o: ["Supply, because gas is an input", "Demand, because gas price affects how attractive electric cars are to buyers", "Both curves", "Neither curve"],
  a: 1, e: "Example 1: gas price does not change the cost of making electric cars, so only demand shifts (to the right).",
  g: { d: { subs: 8 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "The price of gasoline rises, shifting demand for electric cars right. The result is:",
  o: ["Higher price, higher quantity of electric cars", "Lower price, lower quantity", "Higher price, lower quantity", "Lower price, higher quantity"],
  a: 0, e: "A rightward demand shift along a fixed supply curve raises both price and quantity.",
  g: { d: { subs: 8 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "New technology reduces the cost of producing electric cars. The result is:",
  o: ["Price rises, quantity rises", "Price falls, quantity rises", "Price falls, quantity falls", "Price rises, quantity falls"],
  a: 1, e: "Example 2: supply shifts right along a fixed demand curve, so price falls and quantity rises.",
  g: { s: { tech: 8 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "Gas prices rise AND new technology cuts production costs for electric cars. Both curves shift right. The effect on quantity is ______ and the effect on price is ______.",
  o: ["ambiguous; a rise", "a rise; ambiguous", "a fall; a fall", "ambiguous; ambiguous"],
  a: 1, e: "Example 3: both shifts raise Q. Demand pushes P up while supply pushes P down, so the net effect on P depends on which shift is larger.",
  g: { d: { subs: 8 }, s: { tech: 8 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "Both demand and supply for electric cars increase. If demand increases MORE than supply, the price will:",
  o: ["Rise", "Fall", "Stay the same", "Cannot be determined"],
  a: 0, e: "The larger demand shift dominates, so price rises (quantity rises either way).",
  g: { d: { subs: 12 }, s: { tech: 4 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "Both demand and supply for electric cars increase. If supply increases MORE than demand, the price will:",
  o: ["Rise", "Fall", "Stay the same", "Cannot be determined"],
  a: 1, e: "The larger supply shift dominates, so price falls (quantity still rises).",
  g: { d: { subs: 4 }, s: { tech: 12 }, market: "electric cars" } },
{ cat: "Three-step analysis",
  q: "Sellers of music downloads negotiate lower royalties per song. Using the three steps, what happens in the download market?",
  o: ["Demand shifts right; P and Q rise", "Supply shifts right; P falls and Q rises", "Supply shifts left; P rises", "Demand shifts left; P and Q fall"],
  a: 1, e: "Active Learning 3B: royalties are a cost of production, so supply shifts right. Price falls, quantity rises.",
  g: { s: { inputs: -8 }, market: "music downloads" } },
{ cat: "Three-step analysis",
  q: "The price of music CDs falls. Using the three steps, what happens in the market for music downloads?",
  o: ["Demand shifts left; P and Q both fall", "Demand shifts right; P and Q both rise", "Supply shifts left; P rises", "Nothing changes"],
  a: 0, e: "Active Learning 3A: CDs are a substitute, so demand for downloads shifts left. Price and quantity both fall.",
  g: { d: { subs: -8 }, market: "music downloads" } },
{ cat: "Three-step analysis",
  q: "CD prices fall AND royalties fall at the same time. In the download market, demand shifts left and supply shifts right. The result is:",
  o: ["P falls; effect on Q is ambiguous", "Q falls; effect on P is ambiguous", "P and Q both fall", "P and Q both rise"],
  a: 0, e: "Active Learning 3C: both shifts push price down. Lower demand reduces Q but higher supply raises Q, so Q is ambiguous.",
  g: { d: { subs: -8 }, s: { inputs: -8 }, market: "music downloads" } },
{ cat: "Three-step analysis",
  q: "Demand for lattes decreases and supply of lattes decreases at the same time. The effect on quantity is ______ and the effect on price is ______.",
  o: ["a fall; ambiguous", "ambiguous; a fall", "a rise; a rise", "ambiguous; ambiguous"],
  a: 0, e: "Both shifts lower Q. Lower demand pushes P down but lower supply pushes P up, so P is ambiguous.",
  g: { d: { income: -8, incomeType: "normal" }, s: { inputs: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "Demand for lattes increases and supply of lattes decreases at the same time. The result is:",
  o: ["P rises; Q ambiguous", "Q rises; P ambiguous", "P and Q both rise", "P and Q both fall"],
  a: 0, e: "Both shifts push price up. Higher demand raises Q while lower supply reduces Q, so quantity is ambiguous.",
  g: { d: { buyers: 8 }, s: { inputs: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "A frost destroys much of the coffee bean crop (input prices rise) while a health study makes lattes more popular. In the latte market:",
  o: ["Supply shifts left, demand shifts right, price rises", "Supply shifts right, demand shifts left, price falls", "Only supply shifts", "Only demand shifts"],
  a: 0, e: "Two events, two shifts. Both push price up; quantity is ambiguous.",
  g: { d: { tastes: 8 }, s: { inputs: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "Incomes fall (lattes are normal) and, separately, several new coffee shops open. The effect on price is:",
  o: ["A rise", "A fall", "Ambiguous", "Zero"],
  a: 1, e: "Lower demand and higher supply both push price down. Quantity is ambiguous.",
  g: { d: { income: -8, incomeType: "normal" }, s: { sellers: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "Which of the following events would shift the SUPPLY curve for lattes but NOT the demand curve?",
  o: ["A rise in buyers' incomes", "A rise in the price of coffee beans", "A rise in the price of cappuccinos", "A new fashion for drinking lattes"],
  a: 1, e: "Coffee beans are an input. The other three are demand-side variables.",
  g: { s: { inputs: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "Which of the following would shift the DEMAND curve for lattes but NOT the supply curve?",
  o: ["Baristas' wages rise", "A new espresso machine is invented", "The price of pastries (a complement) falls", "Two coffee shops close"],
  a: 2, e: "Pastry prices affect buyers, not sellers' costs. The other three are supply-side variables.",
  g: { d: { comps: -8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "A rightward shift in demand, with supply unchanged, causes which movement along the supply curve?",
  o: ["Sellers move up along the supply curve to a higher P and higher Q", "Sellers move down along the supply curve", "The supply curve shifts right", "No movement"],
  a: 0, e: "When P rises, producers supply more even though the supply curve itself has not shifted. Always separate shifts from movements.",
  g: { d: { buyers: 8 }, market: "lattes" } },
{ cat: "Three-step analysis",
  q: "A leftward shift in supply, with demand unchanged, causes:",
  o: ["A movement up along the demand curve: higher P, lower Q", "A movement down along the demand curve", "The demand curve to shift left", "No change in price"],
  a: 0, e: "Lower supply raises price, and buyers respond by moving up their demand curve to a smaller quantity.",
  g: { s: { inputs: 8 }, market: "lattes" } },
{ cat: "Prices allocate resources",
  q: "In a market economy, what guides economic decisions and allocates scarce resources?",
  o: ["Government planners", "Equilibrium prices, which act as signals", "Advertising agencies", "Random chance"],
  a: 1, e: "Prices adjust to balance supply and demand, and those prices signal where resources are most valued." },
{ cat: "Prices allocate resources",
  q: "'Markets are usually a good way to organize economic activity' mainly because:",
  o: ["Prices are always low", "Prices adjust to balance supply and demand and direct resources to their most valued uses", "Everyone gets the same amount", "Firms never earn profits"],
  a: 1, e: "Price signals coordinate the decisions of millions of buyers and sellers without central direction." },
{ cat: "Prices allocate resources",
  q: "After a hurricane, the price of bottled water rises sharply in the affected area. According to the supply-and-demand model, the higher price:",
  o: ["Signals sellers to bring more water to the area and buyers to conserve it", "Has no effect on behavior", "Shifts the demand curve left", "Means the market has failed"],
  a: 0, e: "A higher price is a signal: it raises quantity supplied and lowers quantity demanded, moving the market toward a new equilibrium.",
  g: { d: { buyers: 12 }, market: "bottled water" } },
{ cat: "Demand",
  q: "Sam's individual demand and the market demand curve differ in that:",
  o: ["Sam's curve slopes upward", "The market curve is the horizontal sum of every buyer's curve, so it lies farther to the right", "The market curve is steeper because it has more buyers", "There is no difference"],
  a: 1, e: "At each price the market quantity is the total across all buyers, so the market curve is to the right of any single buyer's curve." },
{ cat: "Supply",
  q: "Starbucks' individual supply and the market supply curve differ in that:",
  o: ["The market curve is the horizontal sum of all sellers' curves and lies farther to the right", "Starbucks' curve slopes downward", "The market curve does not obey the law of supply", "There is no difference"],
  a: 0, e: "At each price the market quantity supplied is the total across all sellers." },
{ cat: "Surplus & shortage",
  q: "Set the simulator price to $6 with no shifts. Which statement is correct?",
  o: ["There is a shortage of 24 lattes", "There is a surplus of 24 lattes", "The market is in equilibrium", "There is a surplus of 6 lattes"],
  a: 1, e: "At $6, QD = 6 and QS = 30, so the surplus is 30 − 6 = 24 lattes.",
  g: { price: 6, market: "lattes" } },
{ cat: "Surplus & shortage",
  q: "Set the simulator price to $0 with no shifts. Which statement is correct?",
  o: ["Shortage of 24 lattes", "Surplus of 24 lattes", "Equilibrium", "Shortage of 16 lattes"],
  a: 0, e: "At $0, QD = 24 and QS = 0, so the shortage is 24 lattes.",
  g: { price: 0, market: "lattes" } },
{ cat: "Equilibrium",
  q: "Demand increases by 8 lattes at every price (QD = 32 − 3P). If the price stayed at the old equilibrium of $3, the market would have:",
  o: ["A surplus of 8", "A shortage of 8", "Equilibrium", "A shortage of 15"],
  a: 1, e: "At $3, QD = 32 − 9 = 23 but QS = 15, a shortage of 8. This shortage is what pushes the price up to the new equilibrium of $4.",
  g: { d: { buyers: 8 }, price: 3, market: "lattes" } },
{ cat: "Equilibrium",
  q: "Supply increases by 8 lattes at every price (QS = 5P + 8). If the price stayed at the old equilibrium of $3, the market would have:",
  o: ["A shortage of 8", "A surplus of 8", "Equilibrium", "A surplus of 23"],
  a: 1, e: "At $3, QS = 23 but QD = 15, a surplus of 8. Sellers cut prices until the new equilibrium of $2 is reached.",
  g: { s: { tech: 8 }, price: 3, market: "lattes" } },
{ cat: "Demand shifters",
  q: "The government raises the tax on cigarettes so their price rises 10%. Studies show smoking falls about 4% (12% for teenagers). This is an example of:",
  o: ["A leftward shift in the demand for cigarettes", "A decrease in quantity demanded, a movement along the demand curve", "A rightward shift in supply", "A change in tastes"],
  a: 1, e: "A higher price moves buyers along their demand curve. Compare this with health warnings, which shift the curve.",
  g: { price: 5, market: "cigarettes" } },
{ cat: "Supply shifters",
  q: "Which event would make the supply curve for lattes shift to the LEFT?",
  o: ["A fall in the price of milk", "A new, faster espresso machine", "A rise in baristas' wages", "More coffee shops opening"],
  a: 2, e: "Higher wages are a higher input price, which reduces supply. The other three increase supply.",
  g: { s: { inputs: 8 }, market: "lattes" } },
{ cat: "Demand shifters",
  q: "Which event would make the demand curve for lattes shift to the LEFT?",
  o: ["A rise in income (lattes are normal)", "A fall in the price of cappuccinos (a substitute)", "A fall in the price of pastries (a complement)", "More buyers entering the market"],
  a: 1, e: "A cheaper substitute pulls buyers away from lattes, reducing demand. The other three increase demand.",
  g: { d: { subs: -8 }, market: "lattes" } }
];
